spring.datasource.url=postgresql://sports_g3pu_user:oZ78W1fVtyBdf2cYK9WH2yHHgo8owplf@dpg-d7v2erjrjlhs73ae9vt0-a/sports_g3pu
spring.datasource.username=sports_g3pu_user
spring.datasource.password=oZ78W1fVtyBdf2cYK9WH2yHHgo8owplf

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}